####################### Horizons ##########################

# main menu
[[main]]
weight = 1
name = "Menu"
url = "/it/"

[[main]]
weight = 2
name = "Programma"
url = "programma"

[[main]]
weight = 3
name = "Archivi"
url = "archivi"
