####################### navigation ##########################

# main menu
[[main]]
weight = 1
name = "Menu"
url = "/"

[[main]]
weight = 2
name = "Programme"
url = "programme"

[[main]]
weight = 3
name = "Archives"
url = "archives"

