####################### navigation ##########################

# main menu
[[main]]
weight = 1
name = "Home"
url = ""

[[main]]
weight = 2
name = "Schedule"
url = "schedule"

[[main]]
weight = 3
name = "Archives"
url = "archives"

[[main]]
weight = 4
name = "Contacts"
url = "contacts"